### PR TITLE
Fix faucet, better errors

### PR DESCRIPTION
**Pull request by shannonwells**
## Problem

Needed a bit better errors, but really, needed to get the Paseo faucet working again.

## Solution
* update all `@polkadot*` packages
* update any other needed packages because of that
* make any necessary changes as a result
* validate the address before calling fetch.  If it's invalid, make a nice message.
* Be smarter about detecting some errors.
* Don't keep a .env file around

### CODE REVIEW

**Review by wilwade — APPROVED** [review]
Looks good to me.

- Read through code only

**Review by claireolmstead — APPROVED** [review]
LGTM!

**Review by aramikm — APPROVED** [review]
Looks good to me. Thanks for fixing this.

**Comment by shannonwells** [comment]
Related to #22 although there might be some other improvements.

**Pull request merged**
